version: '3'
services:
  wed:
    build: .
    container_name: guestbook
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_started
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - "5432:5432"

